disabled_rules:
 - trailing_whitespace
 - line_length
 - function_body_length
 - force_try
 - large_tuple
opt_in_rules:
 - convenience_type
 - empty_count
 - empty_string
 - fatal_error_message
 - first_where
 - modifier_order
 - toggle_bool
 - closure_spacing
 - trailing_closure
 - xct_specific_matcher
 - vertical_whitespace_opening_braces
 - vertical_whitespace_closing_braces
 - vertical_parameter_alignment
 - unneeded_parentheses_in_closure_argument
 - redundant_string_enum_value
 - redundant_nil_coalescing
 - reduce_into
 - reduce_boolean
 - raw_value_for_camel_cased_codable_enum
 - private_outlet
 - private_action
 - prefer_self_type_over_type_of_self
 - pattern_matching_keywords
 - override_in_extension
 - overridden_super_call
 - operator_usage_whitespace
 - nslocalizedstring_require_bundle
 - nslocalizedstring_key
 - no_grouping_extension
 - no_extension_access_modifier
 - lower_acl_than_parent
 - literal_expression_end_indentation
 - let_var_whitespace
 - last_where
 - joined_default_parameter
 - indentation_width
 - identical_operands
 - function_default_parameter_at_end
 - flatmap_over_map_reduce
 - file_types_order
 - file_name_no_space
 - fallthrough
 - explicit_self
 - contains_over_filter_count
 - contains_over_filter_is_empty
 - contains_over_first_not_nil
 - contains_over_range_nil_comparison
 - collection_alignment
 - closure_end_indentation
 - attributes
 - array_init 
excluded:
 - Pods
reporter: "xcode"
