name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        gem install cocoapods
        pod install
        ls -l /Applications/ | grep Xcode
        sudo xcode-select -switch /Applications/Xcode_11.4.app
        xcodebuild -version
        instruments -s devices
    - name: Lint
      run: |
        set -o pipefail && ./Pods/SwiftLint/swiftlint lint --strict | sed -E "s/$(pwd|sed 's/\//\\\//g')\///" | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 file=\1,line=\2,col=\3::\5/'
    - name: Build
      if: github.ref == 'ref/head/master'
      run: |
        xcodebuild -workspace CoronaTex.xcworkspace -scheme CoronaTex -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest' build
    - name: Test
      run: |
        xcodebuild -workspace CoronaTex.xcworkspace -scheme CoronaTex -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest' test
